- name: install PHP5 packages  
  apt: pkg={{ item }} state=present
  with_items:
    - php5-mysql
    - php5-xcache
    - php5-xdebug
    - php5-curl
    - php5-cli
    - php5-intl
    - php5-gd

- name: install php5-fpm
  apt: pkg=php5-fpm state=present
